<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.dbsearchaccel</groupId>
        <artifactId>db-search-accel</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dsa-sdk</artifactId>
    <name>DSA SDK</name>
    <description>Business integration SDK - Spring Boot Starter</description>

    <dependencies>
        <dependency>
            <groupId>io.github.dbsearchaccel</groupId>
            <artifactId>dsa-common-model</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.dbsearchaccel</groupId>
            <artifactId>dsa-core-route</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
