server:
  port: 8080

spring:
  application:
    name: dsa-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

logging:
  level:
    io.github.dbsearchaccel: DEBUG
    root: INFO
